version: '2.4'

services:

  docker-tutorial-app:
    container_name: docker-tutorial-app-c
    image: registry.cn-shanghai.aliyuncs.com/leon-pu/leon-docker-learn:latest
    build:
      context: .
      dockerfile: image/Dockerfile
    volumes:
      - "/var/docker-tutorial-app/tmp:/app/tmp"
    environment:
      - PORT=3000
    ports:
      - "3000:3000"