version: '3.5'

services:

  docker-learn-app1:
    container_name: docker-learn-app1-c
    image: docker-learn-app1:latest
    build:
      context: .
      dockerfile: ./packages/app1/Dockerfile
    ports:
      - 8301:80