version: '3.5'

services:
  
  simple-httpserver:
    container_name: simple-httpserver-c
    image: simple-httpserver:latest
    build:
      context: .
      dockerfile: ./simple-httpserver/Dockerfile
    ports:
      - 8090:8090
    restart: always